# Generated by Django 3.1.3 on 2020-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
