# Generated by Django 3.1.3 on 2020-11-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201127_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='commentid',
            new_name='sno',
        ),
    ]
